dist: xenial
sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

stages:
  - linting
  - test

cache:
  directories:
    - "$HOME/.cache/pre-commit"

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v

script:
  - pytest . --cov

jobs:
  include:
    - stage: lint
      install:
        - pip install --upgrade pip
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
