site_name: Iambic
site_author: Sean D Stewart
copyright: "Copyright &copy; 2019 - 2020 Sean Stewart"
site_url: https://iambic.seandstewart.io
repo_url: https://github.com/seandstewart/iambic
repo_name: seandstewart/iambic
theme:
  name: "material"
  favicon: "img/favicon.ico"
  logo: "img/icons8-verified-scroll-64.png"
  palette:
    primary: "teal"
    accent: "amber"
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
  feature:
    tabs: true
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      permalink: "#"
  - smarty
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
extra:
  social:
    - type: "github"
      link: "https://github.com/seandstewart/website"
    - type: "twitter"
      link: "https://twitter.com/MrSeanStewart"
    - type: "linkedin"
      link: "https://linkedin.com/in/seandstewart"
  manifest: "static/favicon/site.webmanifest"
